// <auto-generated />
using System;
using ChildhoodVaccination.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ChildhoodVaccination.Migrations
{
    [DbContext(typeof(ChildhoodVaccinationDbContext))]
    [Migration("20181019184631_InitialAdd")]
    partial class InitialAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ChildhoodVaccination.Models.Child", b =>
                {
                    b.Property<long>("ChildID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<long>("DoctorID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("HospitalID");

                    b.Property<string>("IIN")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<string>("Paternity")
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<byte[]>("Photo");

                    b.Property<long>("ScheduleID");

                    b.Property<DateTime>("Updated");

                    b.HasKey("ChildID");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("ChildhoodVaccination.Models.Hospital", b =>
                {
                    b.Property<long>("HospitalID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<DateTime>("Updated");

                    b.HasKey("HospitalID");

                    b.ToTable("Hospitals");
                });
#pragma warning restore 612, 618
        }
    }
}
